
services:
  nginx:
    image: nginx:latest
    container_name: nginx_bcx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d/base.conf:/etc/nginx/templates/base.conf.template
#      - ../nginx/conf.d/base.conf:/etc/nginx/conf.d/base.conf
      - ../logs/nginx:/var/log/nginx
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped
    env_file:
      - .env


  bot:
    build:
      context: ..
      dockerfile: docker/dockerfiles/DockerfileBot
      args:
        - --no-cache
    container_name: bot_bcx
    volumes:
      - ../bot:/app
      - ../logs/bot:/app/logs
    restart: unless-stopped
    env_file:
      - .env


  certbot:
    image: certbot/certbot
    container_name: certbot_bcx
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt


  certbot-renew:
    image: certbot/certbot
    container_name: certbot_renew_bcx
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ../logs/certbot:/var/log/letsencrypt
    entrypoint: sh -c
    command: >
      "trap exit TERM; while :; do certbot renew --quiet >> /var/log/letsencrypt/renew.log 2>&1; sleep 12h & wait $${!}; done;"
    restart: unless-stopped

