
services:
#  db:
#    image: postgis/postgis:latest
#    container_name: db_pnx
#    volumes:
#      - ../data:/var/lib/postgresql/data
#    restart: unless-stopped
#    env_file:
#      - .env
#
#
#  pgadmin:
#    image: elestio/pgadmin
#    container_name: pgadmin_pnx
#    ports:
#      - "8080:80"
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    restart: unless-stopped
#    env_file:
#      - .env


  nginx:
    image: nginx:latest
    container_name: nginx_bcx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d/base.conf:/etc/nginx/conf.d/base.conf
      - ../logs/nginx:/var/log/nginx
    restart: unless-stopped
#    depends_on:
#      - web


#  redis:
#    image: redis:latest
#    container_name: redis_pnx
#    volumes:
#      - redis_data:/data


  bot:
    build:
      context: ..
      dockerfile: docker/dockerfiles/DockerfileBot
      args:
        - --no-cache
    container_name: bot_bcx
    volumes:
      - ../bot:/app
      - ../logs/bot:/app/logs
    restart: unless-stopped
#    depends_on:
#      - db
    env_file:
      - .env


volumes:
  pgadmin_data:
  redis_data:
    driver: local
